### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by marip8**
This PR updates the ROS interface singleton pattern to allow the plugin library from this library to be loaded dynamically from within Python and for downstream custom plugins to be able to link against the interface implementations in this repo. This PR partially addresses #13. My guess is that the primary issue was that the `extern` declaration of the node singleton. Since the node was provided in the c++ reach study executable (and not in the library itself), the node singleton looked like an undefined reference to any other executable that tried to load it.

Although this PR allows ROS2-enabled plugins to be loaded in Python, they won't actually work in a Python script because `rclcpp::init` needs to be called first with the contents of `argv` (i.e. parameters, etc.). I tried calling `rclpy.init()` in the Python script instead (see below), but that doesn't seem to do the trick. I think we'll need to add a small Python interface to this repo for invoking `rclcpp::init` from Python. I propose that be done in a separate PR

```python
import yaml
from reach import runReachStudy, PluginLoader
import rclpy
import sys


def main():
    rclpy.init(args=sys.argv)
    if not rclpy.ok():
        raise RuntimeError('ROS is not running')

    yaml_path = 'config/reach_study.yaml'
    with open(yaml_path) as f:
        config = yaml.safe_load(f)

    loader = PluginLoader()
    loader.search_libraries_env = 'REACH_PLUGINS'

    # Works correctly now
    solver = loader.createIKSolverFactoryInstance('MoveItIKSolver')

    # Fails because `rclcpp::ok()` returns false in the c++ plugin library, even though `rclpy.init` was called in this executable
    res = runReachStudy(config)


if __name__ == '__main__':
    main()

```

### CODE REVIEW

**Comment by marip8** [comment]
@SammyRamone can you review and test on your machine?

**Comment by SammyRamone** [comment]
> @SammyRamone can you review and test on your machine?

Thanks a lot for the effort you put into fixing this weird issue!
I will test it in a few minutes and get back to you.
About the rclcpp::init: You are correct, it is not enough to call the Python version. I encountered the same issue in a different project. We also fixed it by having a small method that just calls the C++ init. It is also possible to check if the init method was already called an just call it in this case (see [here](https://github.com/bit-bots/bitbots_motion/blob/e0d78d97e7c84028239a1419b5011912d7ec5191/bitbots_quintic_walk/src/walk_pywrapper.cpp#L8-L11) for an example)

**Comment by SammyRamone** [comment]
The code works (both for the Python interface as well as through normal ROS 2 calls) 🥳 

For the init problem, I think that just having a small C++ method with Python interface is the best solution. There are some methods to optain `argv` from any part of the code (in Linux there is the pseudo file `/proc/self/cmdline`, in Windows there is `GetCommandLineA()`), however not in all use cases the `argv` of the process are the `argv` that you want to pass to ROS. Having a method makes things more flexible.
I would also add anoher method to this Python interface that allows manual setting of parameters to the C++ ROS node object (that was what I planned to do in my code as I basically want to change IK parameters during runtime).

However, I agree that this can be resolved in a second PR. If you want to, I can programm it.

**Comment by marip8** [comment]
> The code works (both for the Python interface as well as through normal ROS 2 calls)

Excellent; I'll go ahead and merge then

> I would also add anoher method to this Python interface that allows manual setting of parameters to the C++ ROS node object (that was what I planned to do in my code as I basically want to change IK parameters during runtime).

Good point. I've used the Python interface in the past to run a series of reach studies where I changed some ROS parameters in between runs, so I think that would be a useful addition

> However, I agree that this (+ some dokumentation how to run the ROS 2 plugins from Python) can be resolved in a second PR. If you want to, I can programm it.

Sure, that would be helpful. I'll open an issue about the features we want to expose in the Python interface for reference

**Pull request merged**
